image: "continuumio/miniconda3:4.3.31"

before_script:
  - export PATH="/opt/conda/bin:/usr/local/bin:/usr/bin:/bin:"
  - unset CONDA_DEFAULT_ENV
  - export ANACONDA_HOME=/opt/conda
  - export PATH=/opt/conda/bin:$PATH
  - conda config --add channels defaults
  - conda config --add channels conda-forge
  - conda config --add channels bioconda
   #useful for debugging any issues with conda
  - conda info -a

job1:
  script: "python test/test.py"
