image: continuumio/miniconda3:4.4.10

before_script:
  - export PATH="/opt/conda/bin:/usr/local/bin:/usr/bin:/bin:"
  - unset CONDA_DEFAULT_ENV
  - export ANACONDA_HOME=/opt/conda
  - export PATH=/opt/conda/bin:$PATH
  - conda config --add channels defaults
  - conda config --add channels bioconda
  - conda config --add channels conda-forge
   #useful for debugging any issues with conda
  - conda create --yes -n snakemake snakemake=5.2.2
  - conda info -a

job1:
  script: "python test/test.py"
