###########################
##General parameters#######
###########################

# minimum length of resulting contigs
minlen: 500

# minimum average coverage of contigs (to filter out low frequency contamination)
mincov: 10

###################################################################################
##Package-specific parameters, only change if standard - version above is empty. Otherwise,
##pre-defined standard parameters will be taken
####################################################################################
# Please consult bioconda package manager for possible package versions

seqtk:
  params: -q 0.01

SPAdes:
  params: --only-assembler --careful --threads 8
  krange: 57,97,127 #adjust if you would like to select a different kmer range for spades assembly

QUAST:
  params: --min-contig 500

mlst:
  params: --reduced_tree

prokka:
  params: --centre U --locustag C --compliant
  version: 1.11

kraken:
  params: --quick --db /hpc/local/CentOS7/dla_mm/tools/kraken/db/minikraken_20140330/

krona:
  version: 2.6

checkm: 
  params: --reduced_tree

abricate:
  version: 0.3
