
##General parameters
#minimum length of resulting contigs
minlen: 500
#minimum average coverage of contigs (to filter out low frequency contamination)
mincov: 10

seqtk:
  version: 1.2
  params: -q 0.01

SPAdes:
  params: --only-assembler --careful --threads 8
  version: 3.6.2
  versiontag: V022017SPAdes+spadesversion

QUAST:
  version: 1.1
  params: --min-contig 500

mlst:
  version: 1.1
  params: --reduced_tree


prokka:
  params: --centre UMCU --compliant

kraken:
  version: 1.1
  params: --quick --db /hpc/local/CentOS7/dla_mm/tools/kraken/db/minikraken_20140330/

checkm: 
  params: --reduced_tree
