###########################
##General parameters#######
###########################

# minimum length of resulting contigs
minlen: 500

# minimum average coverage of contigs (to filter out low frequency contamination)
mincov: 10

# remove temporary files after successful analysis. no/yes
remove_temp: yes

seqtk: # trimming 
  params: -q 0.01

SPAdes: # assembly
  params: --only-assembler --careful --threads 8
  krange: 37,57,77 #adjust if you would like to select a different kmer range for spades assembly

QUAST: # assembly quality check
  params: --min-contig 500 

mlst:  # multi-locus sequence typing on WGS
  params: --nopath

abricate: # resistance gene detection
  params: --nopath --minid=90

prokka: # annotation
  params: --force 


multiqc: #reporting
  params: --zip-data-dir --ignore-samples *gff --force
